model:
  model_size: 256
  num_layers: 4
  dropout: 0.1

training:
  batch_size: 8
  learning_rate: 3.0e-4
  warmup_steps: 1000
  n_epochs: 200
  l2: 0.0
  lr_milestones: [125, 150, 175]
  lr_gamma: 0.5

data:
  emg_data_dir: /scratch/cr4206/data/emg_data/emg_data

logging:
  wandb_project: silent_speech_uml
  checkpoint_dir: /scratch/cr4206/checkpoints
