model:
  model_size: 256
  num_layers: 4
  dropout: 0.1

training:
  batch_size: 32
  learning_rate: 3.0e-4
  warmup_steps: 500
  n_epochs: 60
  l2: 0.0
  lr_milestones: [40, 50]
  lr_gamma: 0.5
  log_every_steps: 20

data:
  emg_data_dir: /scratch/cr4206/data/emg_data/emg_data
  librispeech_dir: /scratch/cr4206/data/librispeech

logging:
  wandb_entity: UMLforVideoLab
  wandb_project: UMLvsBaseline
  checkpoint_dir: /scratch/cr4206/checkpoints

uml:
  lambda_uml: 0.5
